version: '2.1'
services:
     elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
       container_name: elasticsearch
       ports: 
        - "9200:9200"

     kibana:
       image: docker.elastic.co/kibana/kibana:6.4.0
       container_name: kibana
       environment:
          - "ELASTICSEARCH_URL=http://elasticsearch:9200"
       depends_on:
          - elasticsearch
       ports: 
          - "5601:5601"

